config/routes.rb
Twitter::Application.routes.draw do

  devise_for :users
  resources :tweets
  resources :users
  
  root "tweets#index"

end

app/models/following.rb
class Following < ActiveRecord::Base

  belongs_to :user
  belongs_to :followed, :class_name => 'User'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  validates :text,  presence: true, 
                    length: { minimum: 2, maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets, dependent: :destroy
  
  has_many :followings
  has_many :friends, :through => :followings, :source => 'followed'

  has_many :followeds, :class_name => 'Following', :foreign_key => 'followed_id'
  has_many :followers, :through => :followeds, :source => :user

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # Lazy way to add new fields to the User
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_filter :authenticate_user!,
    :only => [:new, :create, :destroy]
  
  def new
    @tweet = User.find(current_user).tweets.new
  end
  
  def index
    @tweets = Tweet.find(:all, :order => "id DESC", :limit => 10)
    if user_signed_in?
      @user = User.find(current_user)
    end
  end
  
  def show
    if user_signed_in?
      @user = User.find(current_user)
    end
    @tweet = Tweet.find(params[:id])
  end
  
  def create
    @tweet = User.find(current_user).tweets.new(validate_params)
    if @tweet.save
      redirect_to @tweet
    else
      render 'new'
    end
  end
  
  def destroy
    @tweet = User.find(current_user).tweets.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path
  end
  
  private
    def validate_params
      return params.require(:tweet).permit(:text)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def show
    @user = User.find(params[:id])
    @me = User.find(current_user)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/tweets/index.html.erb
<h1>Latest Tweets</h1>
<%= link_to "Post new tweet", action: "new" %>
<ul>
  <% @tweets.each do |tweet| %>
    <li>
      <p><%= link_to( tweet.text, tweet) %></p>
    </li>
  <% end %>
</ul>

<% if @user %>
  <%= link_to 'Logout', destroy_user_session_path, :method => :delete  %> 
<% end %>
<% if @user %>
  <%= link_to 'Account settings', edit_user_registration_path  %> 
<% end %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<% if @tweet.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited
    this post from being saved:</h2>
  <ul>
  <% @tweet.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

<%= form_for :tweet, url: tweets_path do |f| %>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/tweets/show.html.erb
<%= link_to 'Home', tweets_path %>

<p>
  <strong>
    <% if @tweet.user %>
      <%= link_to '@' + @tweet.user.name, @tweet.user %> 
    <% end %>
    says:
  </strong>
  <span>
    <%= @tweet.text %>
  </span>
</p>

<% if @tweet.user && @user && (@user.id == @tweet.user.id) %>
  <%= link_to 'Delete', tweet_path(@tweet),
                      method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/users/show.html.erb
<%= link_to 'Home', tweets_path %>

<h1><%= @user.name %></h1>
<p>
  <span>Email:</span> <%= @user.email %>
</p>

<h3>Follows:</h3>
<% @user.followings.each do |follower| %>
  <p>
    <h4><% follower.name %></h4>
    <span>Email:</span> <%= follower.email %>
  </p> 
<% end %>